### ISSUE TITLE
Documentation on RayExecutor?

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allentune#13]
Hey, 
It is not clear how to use RayExecutor,
Where can I find a working example or documentation on how to use it.
Thanks

**Comment by kernelmachine** [comment]
Hey there, you can check out the docs here: Https://docs.ray.io/en/latest/tune/index.html, there is a bare-bones implementation of the library in this repo. Lots of things could be added, e.g. sophisticated scheduling.
