### ISSUE TITLE
how to use allennlp 1.1.0 with allentune

### ISSUE THREAD

**Issue by BettyHcZhang** [allenai/allentune#14]
Hi ,I'm fans of allentune. I installed allennlp=1.1.0, which should based on torch=1.6 , but alllentune requires  torch=1.5. It is not compatible currently.  
If I go back to allennlp=1.0.0, some of my code should make change, such as _BertTokenizer.from_pretrained_ could not use any more.
Is there any suggestions?
Thank you very much!

**Comment by chloefresh** [comment]
Hi, how do you solve this? thx~
